### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#15]
**Is your feature request related to a problem? Please describe.**
Clarification on if this is purely a NodeJS web app or an actual NodeJS desktop application.

**Describe the solution you'd like**
Possibly change the name of the repo to be something like ``KentFlixWebClient`` and provide info in the Readme. 

**Additional context**

**Comment by HenryBrown0** [comment]
This is going to be a progress web application. However please feel free to create a desktop application using the [api](https://github.com/KentCompSoc/KentFlixServer/).

I've updated the readme to hopefully describe this better, I've not added screenshots yet as the website will change in the next month.

You can also see the [server](https://github.com/KentCompSoc/KentFlixServer/)
