### ISSUE TITLE
Privacy Policy to comply with GDPR

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#21]
**Is your feature request related to a problem? Please describe.**
Because the web app is handling usernames and passwords and dealing with some kind of authentication, to be compliant under GDPR we need a privacy policy which allows us to collect and store the information.

**Comment by HaywoodSolutions** [comment]
In progress, would be under 
https://kentflix.com/licences/

**Comment by AluminiumTech** [comment]
Also, just nit-picking but typo on your legal page

``responces`` should be ``responses``
