### ISSUE TITLE
Login with Kent Email fails

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#23]
**Describe the bug**

**To Reproduce**
1. Install via NPM
2. Click on Login
3. Enter correct login details

**Expected behavior**
User successfully logs in and is able to view videos.

**Screenshots**
![login_fail](https://user-images.githubusercontent.com/14107316/48486678-20146e80-e814-11e8-910e-625e57a091bb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Mint 19
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 63.0

**Comment by HenryBrown0** [comment]
@AluminiumTech It doesn't look like you've registered with KentFlix yet, try registering first.
I need to make this easier to understand, any suggestions?

**Comment by AluminiumTech** [comment]
@HenryBrown0
I was under the impression that just logging in with existing Kent login details would work.

Perhaps an option to "Login with Kent IT Account" would help make things more clear. Although I realize this may be difficult to setup.

And possibly also options for Logging in via GitHub, Google, Facebook, Twitter etc.

**Comment by HenryBrown0** [comment]
@AluminiumTech We currently can't give users the option to login with their Kent IT Account.
In later releases we may implement other methods of logging in but we would still require a kent email address to activate the account.

**Comment by AluminiumTech** [comment]
@HenryBrown0  Then perhaps for initial release just inform people that they need to register.
