### ISSUE TITLE
Make more user-friendly by hosting web app on GitHub Pages or server

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#25]
**Is your feature request related to a problem? Please describe.**
The installation process right now is not friendly for non-techies. This could be remedied by hosting the web app so that it could easily be navigated to by entering a URL in a browser.

**Describe the solution you'd like**
Host the web app on something like GitHub pages or a web server so that people can easily navigate to a URL in order to access Kentflix.

**Comment by HenryBrown0** [comment]
Once v1.0.0-beta is ready it will accessible like a normal website
