### ISSUE TITLE
npm start now takes a ridiculous amount of time to execute

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#31]
**Describe the bug**
Running npm start now takes a ridiculously long amount of time. Even on a system with a lot of cores and threads (specifically 8 cores and 16 threads), 

**To Reproduce**
1. Run npm start in KentFlixClient folder after latest commit
2. See npm start taking ages to execute

**Expected behavior**
NPM start causing Kentflix to start almost instantly.

**Screenshots**
![image](https://user-images.githubusercontent.com/14107316/48763427-33588b80-eca5-11e8-926a-b9981f129a8d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu] Windows 10
 - Browser [e.g. Chrome, Safari, Firefox, Edge] Firefox
 - Version [e.g. 60.0] 63.0

**Comment by HenryBrown0** [comment]
@AluminiumTech which branch are you using?

**Comment by AluminiumTech** [comment]
@HenryBrown0  Master. This might be the first time I've tried running Kentflix on Windows. Running it on Linux Mint, it almost instantly loads compared to this.

**Comment by HenryBrown0** [comment]
@AluminiumTech This is most likely a Windows vs Linux optimisation difference with Node.js. The master branch hasn't been changed since the last time you used it
