### ISSUE TITLE
What's the official email for Kentflix?

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#32]
**Your question**
Hi, I'm working on the Privacy Policy and I wanted to know what the official email of KentFlix is?

Thanks.

**Comment by HenryBrown0** [comment]
I expect: compsoc@kent.ac.uk
@HaywoodSolutions is this correct?

**Comment by HaywoodSolutions** [comment]
Yes

**Comment by AluminiumTech** [comment]
@HenryBrown0  @HaywoodSolutions  And does anybody monitor the email on a regular basis?

**Comment by HaywoodSolutions** [comment]
Yes I do
