### ISSUE TITLE
Do we need to create a new account now?

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#35]
**Your question**
Now that KentFlix official website has been launched, do we need to create a new account?

Because logging in with my credentials is showing a black screen
![login_blank](https://user-images.githubusercontent.com/14107316/48779208-fdc89800-ecce-11e8-85d3-6cc2f6cc8c9f.png)

**Comment by HenryBrown0** [comment]
@AluminiumTech The blank screen is probably due to outdated API's and not an issue with the login as I believe that's stayed the same @HaywoodSolutions . No logins have been deleted from the server

**Comment by HaywoodSolutions** [comment]
@HenryBrown0 @AluminiumTech Thats correct, it is the submodule of the master branch of the [Client Repo](https://github.com/KentCompSoc/KentFlixClient), but once the master has been updated with the new endpoints at [api.kent.ac.uk](api.kent.ac.uk) it will work.

**Comment by HaywoodSolutions** [comment]
Also all endpoints has moved to [api.kentflix.com/v1](api.kentflix.com/v1) from [kentflix.com/api/v1](kentflix.com/api/v1)
