### ISSUE TITLE
React Errors shown after login attempt

### ISSUE THREAD

**Issue by AluminiumTech** [KentCompSoc/KentFlixClient#37]
**Describe the bug**
After the username and password are entered, a bunch of React errors are shown.

**To Reproduce**
1. Installing using ``npm install``
2. Start using ``npm start``
3. See error

**Expected behavior**
To view the dashboard and be able to view a lecture recording

**Screenshots**
![image](https://user-images.githubusercontent.com/14107316/48962860-a8b2ad80-ef7e-11e8-890b-7c6f7b3a80a8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu] Windows 10 64 Bit
 - Browser [e.g. Chrome, Safari, Firefox, Edge] Brave
 - Version [e.g. 60.0] 0.56.15 using Chromium 70.0

**Comment by HenryBrown0** [comment]
@AluminiumTech I can't seem to get this issue on my end but I'm aware of what's causing it. Please check your console for the response from the server (it'll be a password incorrect or network issue I suspect)

**Comment by HenryBrown0** [comment]
@AluminiumTech please confirm issue resolved in #38
